### ISSUE TITLE
O-Wochen-Programm aktualisieren

### ISSUE THREAD

**Issue by 2xB** [fsphys-muenster/homepage-todo#1]
... und Infos von 2017/18 ausblenden

(Von @l-althueser )

**Comment by Kristin-N** [comment]
Ich hab das Programm aktualisiert aber ich weiß nicht wie man die Sponsoren ausblendet

**Comment by 2xB** [comment]
Mit einem neuen Tab für 2020 mit "to be announced"?

**Comment by Kristin-N** [comment]
Ich weiß aber auch nicht mehr wie ich einen Tab hinzufüge. Ich weiß nur wie man Texte bearbeitet und Fachschaftler hinzufügt

**Comment by l-althueser** [comment]
Hilfe findet man hier: https://www.uni-muenster.de/imperia/md/content/ew/imperiahandbuchwwu.pdf
Seite 27 sollte weiterhelfen.

**Comment by Kristin-N** [comment]
Daaaanke! Ich habs geschafft. O-Wochen Seite ist hoffentlich soweit aktualisiert. :)
